### ISSUE TITLE
No image is provided at step 5

### ISSUE THREAD

**Issue by msachi** [node-girls/workshop-cms#36]
(but it is referenced in the index.html)

**Comment by jsms90** [comment]
Image is actually expressly deleted (see picture below), but presumably this was a mistake?
![deletes-image](https://cloud.githubusercontent.com/assets/15656538/20079837/775b3180-a53e-11e6-9138-0fa694ed7f0d.png)

**Comment by msachi** [comment]
Yeah, I noticed, not sure what happened there!

**Comment by claireinez** [comment]
We'll fix this issue this weekend too!

**Comment by claireinez** [comment]
This was fixed in https://github.com/node-girls/workshop-cms/pull/40 so closing now.
