### ISSUE TITLE
CSS file seems to disappear when moving from step 5 to 6

### ISSUE THREAD

**Issue by msachi** [node-girls/workshop-cms#37]
Not sure why that is but many of us lost it at that stage when merging. Might be better to include it also in subsequent steps and not just step 5? I'm not sure how Git deals with merging when files are deleted.

**Comment by msmichellegar** [comment]
Yes, we're aware there are some issues with the git flow aspect of this repo! We are going to restructure the workshop without recommending those doing it checkout at the end of each step, and just include all the assets in the master branch (or one other branch).

**Comment by msachi** [comment]
Ok, great ☺️

**Comment by SavageWilliam** [comment]
How's progress with this issue? FAC9 would love to use this repo as a workshop for FAC10  :smile:

**Comment by claireinez** [comment]
Aw that's great! We'll get a move on and try to do it this weekend. :smiley:

**Comment by claireinez** [comment]
@SavageWilliam and @msachi, we did some work on this over the weekend but there are probably still bugs we haven't spotted. It's currently sitting on the branch https://github.com/node-girls/workshop-cms/tree/fix-git-flow-issues so if you have time, could you try it out and let us know if there are any problems before merging?

**Comment by marisid** [comment]
Hey @claireinez! Thanks for taking the time to improve this really useful tutorial. It's so much better not to have so many steps and include all assets from the beginning as you build the server. I had a look and I couldn't spot any issues. The only thing I noted is that the 'HitCount' image in the readme doesn't appear - something to do with the links maybe?... 

@SavageWilliam @msachi if you have any further comments/issues, please post here.

We are planning to use this repo as a tutorial to FAC10 next Monday, so it would be great if it could be merged to master before then. If not, people could checkout this branch instead of master.

**Comment by msmichellegar** [comment]
Thanks for checking it out @marisid! Wanna pull request @claireinez?

**Comment by marisid** [comment]
Girls, I just realised that the readme (see extract below) has not been updated accordingly after you fixed the git flow issues. 

> The project has been split into steps, which are documented in separate files here on the master branch.
If you run git branch on your machine, you will see there is a branch per step. Write all your code in the relevant git branch for your step.
At the start of each step, you will need to checkout to the next branch on Git.
You will be reminded to do this at the start of each step, like so:
`git checkout [name of a particular branch]`
`git merge [name of previous branch]`

Maybe wanna say that each step builds on top of the other and that there is no need to checkout to different branches but just commit your changes at the end of each step?

**Comment by claireinez** [comment]
@marisid I'm not at a computer today so can't push changes but if you make a PR and assign me, @msmichellegar or @minaorangina, we'll be happy to review!

**Comment by marisid** [comment]
Hey @claireinez - no problem! I've made the changes but have no access to the repo as a contributor. Could you please give me permission to push?

**Comment by msmichellegar** [comment]
@marisid Added you to this repo 👍

**Comment by marisid** [comment]
@msmichellegar I still don't have write access rights :confused: but it's ok, I created a PR from my forked repo :smile: - pls have a look when you can.

**Comment by msmichellegar** [comment]
@marisid Think you need to accept the invite. But that's ok, I'll check out your PR!

![screen shot 2017-03-12 at 10 06 36 pm](https://cloud.githubusercontent.com/assets/10683087/23836441/30edcd9a-0770-11e7-8c69-8bf3f6600c99.png)

**Comment by msmichellegar** [comment]
Going to close this now!

**Comment by marisid** [comment]
Thanks @msmichellegar - sorry I missed the email! But job done anyway:+1:
