### ISSUE TITLE
Modify Node Girls Workshop & Fix Typos from step #6 to #10

### ISSUE THREAD

**Issue by EngAyoosh** [node-girls/workshop-cms#47]
As discussed [here](https://github.com/foundersandcoders/master-reference/issues/631) I proposed the following changes : 
- Fix typos.
- adding links to keyword section
- adding more illustration for some points to be more clear.

Is it ok for me to make a pull request to fix these points?

**Comment by eliasmalik** [comment]
Addressed by #46. Can be closed.

**Comment by claireinez** [comment]
Thanks @eliascodes and @EngAyoosh. Closing now 😃
